import { useNavigate } from "react-router-dom";

function Home() {
  const navigate = useNavigate();

  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)" }}>
      
      {/* Hero Section */}
      <div className="container text-center py-5">
        <div className="py-5">
          <h1 className="display-3 fw-bold text-white mb-3">
            ✈️ AI Itinerary Planner
          </h1>
          <p className="lead text-white mb-2" style={{ fontSize: "1.3rem" }}>
            Plan your perfect trip in seconds
          </p>
          <p className="text-white-50 mb-5">
            Powered by Google Gemini AI
          </p>

          <img 
            src="https://cdn-icons-png.flaticon.com/512/201/201623.png"
            alt="travel illustration" 
            width="180" 
            className="mb-5"
            style={{ filter: "drop-shadow(0px 10px 20px rgba(0,0,0,0.3))" }}
          />

          <div className="d-flex justify-content-center gap-3 mb-5">
            <button 
              className="btn btn-light btn-lg px-5 py-3 fw-bold"
              style={{ borderRadius: "50px" }}
              onClick={() => navigate("/signin")}>
              Sign In
            </button>
            <button 
              className="btn btn-outline-light btn-lg px-5 py-3 fw-bold"
              style={{ borderRadius: "50px" }}
              onClick={() => navigate("/signup")}>
              Sign Up
            </button>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container pb-5">
        <div className="row g-4">
          <div className="col-md-4">
            <div className="card border-0 shadow-lg h-100 text-center p-4"
              style={{ borderRadius: "20px" }}>
              <div style={{ fontSize: "50px" }}>🤖</div>
              <h4 className="fw-bold mt-3">AI Powered</h4>
              <p className="text-muted">Get personalized itineraries generated by Google Gemini AI in seconds</p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="card border-0 shadow-lg h-100 text-center p-4"
              style={{ borderRadius: "20px" }}>
              <div style={{ fontSize: "50px" }}>💰</div>
              <h4 className="fw-bold mt-3">Budget Friendly</h4>
              <p className="text-muted">Enter your budget and get a plan that fits your wallet perfectly</p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="card border-0 shadow-lg h-100 text-center p-4"
              style={{ borderRadius: "20px" }}>
              <div style={{ fontSize: "50px" }}>🗺️</div>
              <h4 className="fw-bold mt-3">Day by Day</h4>
              <p className="text-muted">Get a complete day-by-day schedule with activities and restaurants</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}

export default Home;